#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe orte 8
#$ -N mc4
#$ -v LD_LIBRARY_PATH,MC4_EXE_PATH,OPENMPI

MACHINE_FILE=$TMPDIR/machinefile
awk '/^felsim/ {print $1" slots="$2}' $PE_HOSTFILE > $MACHINE_FILE
cp $MACHINE_FILE .machinefile.last

MC4="$MC4_EXE_PATH/mc4 test7 cmb.tf init.in --info 0 --warn 0 "
CMD="$OPENMPI/bin/mpirun -x LD_LIBRARY_PATH -machinefile $MACHINE_FILE -np $NSLOTS  $MC4 "
echo "Running $CMD"
echo
$CMD