SHELL = /bin/sh

PROG = pow

# **** COMPILER FLAGS ****

####################################################################

all: 
	pghpf -o $(PROG) *hpf

clean:
	rm -fr $(PROG) step-10.dat *.o core *~ *.pdf
