###########################################################################
#
# The IPPL Framework
# 
# This program was prepared by the Regents of the University of
# Visit http://people.web.psi.ch/adelmann/ for more details
#
###########################################################################

SHELL = /bin/sh

UTILITIES = dcpdump

include $(IPPL_ROOT)/lib/$(IPPL_ARCH)/Makefile.app

all: $(UTILITIES)

clean: 
	rm -f $(UTILITIES) $(UTILITIES:=.o) core


###########################################################################
# $RCSfile: Makefile,v $   $Author: adelmann $
# $Revision: 1.1.1.1 $   $Date: 2003/01/23 07:41:39 $
###########################################################################

/***************************************************************************
 * $RCSfile: addheaderfooter,v $   $Author: adelmann $
 * $Revision: 1.1.1.1 $   $Date: 2003/01/23 07:40:17 $
 * IPPL_VERSION_ID: $Id: addheaderfooter,v 1.1.1.1 2003/01/23 07:40:17 adelmann Exp $ 
 ***************************************************************************/

