!-----This routine reads in a 1-dim transfer function generated by CMBFAST
!-----then it spline-fits the transfer function and calculates a 3-dim
!-----transfer function at the values needed in the main code

      subroutine cmbfit1d(nmax,nk,kmax,kmin,trcmbf,
     #                    omegatot,omegab,omegadm)

      implicit none

      integer nmax,nk,ii,jj,mm

      real kk1,tf1,tfnorm,tpiL,rL,kmax,kmin,dk
      real omegatot,omegab,omegadm

      real kk(nmax),tf(nmax),tf2(nmax),trcmbf(nk)
      real tfcdm(nmax),tfbar(nmax)

!hpf$ distribute kk(block)	
!hpf$ distribute trcmbf(block)	
!hpf$ align (:) with kk(:) :: tf,tf2,tfcdm,tfbar

      tpiL=8.0*atan(1.0)/rL

      open(12,file="cmb.tr",status="old")

      do ii=1,nmax
      read(12,*)kk(ii),tfcdm(ii),tfbar(ii)
      enddo

      close(12)

      tf=tfbar*omegab/omegatot+tfcdm*omegadm/omegatot

      call spline(kk,tf,nmax,tf2)

      kk1=kmin
 
      call splint(kk,tf,tf2,nmax,kk1,tf1)	

      tfnorm=tf1

      dk=(kmax - kmin)/(nk-1.0)

      open(13,file="cmb1d.fit")

      do ii=1,nk
    
      kk1=kmin+(ii-1)*dk

      call splint(kk,tf,tf2,nmax,kk1,tf1)

      trcmbf(ii)=tf1/tfnorm

      write(13,*)kk1,trcmbf(ii)	

      enddo

      close(13)
      
      return
      end subroutine

