!-----This routine reads in a 1-dim transfer function generated by CMBFAST
!-----then it spline-fits the transfer function and calculates a 3-dim
!-----transfer function at the values needed in the main code

      subroutine fitlin1d(nmax,nk,kmax,kmin,trcmbf,
     #                    omegatot,omegab,omegadm)

      implicit none

      integer nmax,nk,ii,jj,mm,index

      real kk1,tf1,tfnorm,tpiL,rL,kmax,kmin,dk
      real omegatot,omegab,omegadm,wone,wtwo,trcmbftmp

      real kk(nmax),tf(nmax),trcmbf(nk)
      real tfcdm(nmax),tfbar(nmax)

!hpf$ distribute kk(block)	
!hpf$ distribute trcmbf(block)	
!hpf$ align (:) with kk(:) :: tf,tfcdm,tfbar

      tpiL=8.0*atan(1.0)/rL

      open(12,file="cmb.tr",status="old")

      do ii=1,nmax
      read(12,*)kk(ii),tfcdm(ii),tfbar(ii)
      enddo

      close(12)

      tf=tfbar*omegab/omegatot+tfcdm*omegadm/omegatot

      tfnorm=tf(1)

      dk=(kmax - kmin)/(nk-1.0)

      open(13,file="cmb1d.fit")

      do ii=1,nk
    
      kk1=kmin+(ii-1)*dk

      call locate(kk,nmax,kk1,index)

      wone=(kk(index+1)-kk1)/(kk(index+1)-kk(index))
      wtwo=1.0-wone
      trcmbftmp=wone*tf(index)+wtwo*tf(index+1)


      trcmbf(ii)=trcmbftmp/tfnorm

      write(13,*)kk1,trcmbf(ii)	

      enddo

      close(13)

      return
      end subroutine

