#
# Find IPPL includes and library
#
# IPPL_INCLUDE_DIR - where to find ippl.h
# IPPL_LIBRARY     - qualified libraries to link against.
# IPPL_FOUND       - do not attempt to use if "no" or undefined.

FIND_PATH(IPPL_INCLUDE_DIR Ippl.h
    PATHS
	$ENV{OPAL_DIR}/include
	$ENV{OPAL_HOME}/include
        ENV OPAL_INCLUDE_DIR C_INCLUDE_PATH CPLUS_INCLUDE_PATH
    NO_DEFAULT_PATH
)

FIND_LIBRARY(IPPL_LIBRARY ippl
    PATHS
	$ENV{OPAL_DIR}/lib
	$ENV{OPAL_HOME}/lib
        ENV OPAL_LIBRARY_DIR LIBRARY_PATH
    NO_DEFAULT_PATH
)

find_package_handle_standard_args (IPPL REQUIRED_VARS IPPL_INCLUDE_DIR)
find_package_handle_standard_args (IPPL REQUIRED_VARS IPPL_LIBRARY)
set (IPPL_CMAKE_CXX_FLAGS "-DIPPL_LINUX -DIPPL_STRINGSTREAM -DIPPL_MPI -DMPICH_SKIP_MPICXX -DIPPL_GCC -DIPPL_DONT_POOL -DIPPL_USE_XDIV_RNG -DIPPL_NO_STRINGSTREAM -DPETE_BITWISE_COPY -DIPPL_HAS_TEMPLATED_COMPLEX -DIPPL_USE_STANDARD_HEADERS -DIPPL_USE_PARTIAL_SPECIALIZATION -DIPPL_STDSTL -DIPPL_LONGLONG -DWITH_BRICK -DnoCOMP_GNUOLD -Drestrict=__restrict__ -DNOCTAssert ")
