!-----This routine reads in a 1-dim transfer function generated by CMBFAST
!-----then  spline-fits the transfer function and calculates a 3-dim
!-----transfer function at the values needed in the main code

      subroutine fitlin3d(nmax,nq,rL,trcmbf,omegatot,omegab,omegadm)

      implicit none

      integer nmax,nq,ii,jj,mm,index

      real kk1,tf1,tfnorm,tpiL,rL,omegatot,omegab,omegadm
      real wone,wtwo,trcmbftmp

      real kk(nmax),tf(nmax),trcmbf(nq,nq,nq)
      real tfcdm(nmax),tfbar(nmax)

!hpf$ distribute kk(block)	
!hpf$ distribute trcmbf(*,*,block)	
!hpf$ align (:) with kk(:) :: tf,tfcdm,tfbar

      write(6,*)'enter cmbfit'

      tpiL=8.0*atan(1.0)/rL

      open(12,file="cmb.tr",status="old")

      do ii=1,nmax
      read(12,*)kk(ii),tfcdm(ii),tfbar(ii)
      enddo

      close(12)

      tf=tfbar*omegab/omegatot+tfcdm*omegadm/omegatot

      open(13,file="cmb.check")

      do ii=1,nmax
      write(13,*)kk(ii),tf(ii)/maxval(tf)
      enddo

      close(13)

      tfnorm=tf(1)

      write(6,*)'Tfnorm=',tfnorm

      if(kk(nmax).lt.(tpiL*sqrt(3.0)*nq))then
      write(6,*)'kmax(cmbfast)=',kk(nmax),'kmax(req)=',tpiL*sqrt(3.0)*nq
      write(6,*)'EHH!! k-range in cmb.tr insufficient! Code will stop'
      stop
      endif

      open(14,file="cmb.fit")

      do ii=1,nq
      do jj=1,nq
      do mm=1,nq  
    
      kk1=tpiL*((ii-1)**2+(jj-1)**2+(mm-1)**2)**(0.5)   

      call locate(kk,nmax,kk1,index)

      wone=(kk(index+1)-kk1)/(kk(index+1)-kk(index))
      wtwo=1.0-wone
      trcmbftmp=wone*tf(index)+wtwo*tf(index+1)


      trcmbf(ii,jj,mm)=trcmbftmp/tfnorm

      write(14,*)kk1,trcmbf(ii,jj,mm)

      enddo
      enddo
      enddo

      close(14)
      
      return
      end subroutine
