#!/bin/bash
mkdir -p data
tail -14 $0 > script.tmp
change -f "NODES"  "$1" ./script.tmp
change -f "PPERNODE"  "$2" ./script.tmp
change -f "NAME"  "$3" ./script.tmp
np=$(($1 * $2))
change -f "NP"  "$np" ./script.tmp
llsubmit ./script.tmp
rm ./script.tmp
exit
#!/usr/bin/csh
#@ job_name        = NAME-NP
#@ output          = NAME-NP.out
#@ error           = NAME-NP.err
#@ job_type        = parallel
#@ class           = regular_n3e 
#@ tasks_per_node  = PPERNODE 
#@ node            = NODES
#@ wall_clock_limit= 2:30:00
#@ notification    = complete
#@ network.MPI     = csss,not_shared,us
#@ queue
setenv MP_PIPE_SIZE 16
poe+ ./run 
