#! /bin/csh
# ACL:license
#  ----------------------------------------------------------------------
#  This software and ancillary information (herein called "SOFTWARE")
#  called PAWS (Parallel Application WorkSpace) is made available under
#  the terms described here.  The SOFTWARE has been approved for release
#  with associated LA-CC Number LA-CC-98-33.
#  
#  Unless otherwise indicated, this SOFTWARE has been authored by an
#  employee or employees of the University of California, operator of the
#  Los Alamos National Laboratory under Contract No.  W-7405-ENG-36 with
#  the U.S. Department of Energy.  The U.S. Government has rights to use,
#  reproduce, and distribute this SOFTWARE, and to allow others to do so.
#  The public may copy, distribute, prepare derivative works and publicly
#  display this SOFTWARE without charge, provided that this Notice and
#  any statement of authorship are reproduced on all copies.  Neither the
#  Government nor the University makes any warranty, express or implied,
#  or assumes any liability or responsibility for the use of this
#  SOFTWARE.
#  
#  If SOFTWARE is modified to produce derivative works, such modified
#  SOFTWARE should be clearly marked, so as not to confuse it with the
#  version available from LANL.
#  
#  For more information about PAWS, send e-mail to paws@acl.lanl.gov,
#  or visit the PAWS web page at http://www.acl.lanl.gov/paws/.
#  ----------------------------------------------------------------------
# ACL:license

# run the program with the given arguments
echo "-------------------------------------------"
echo "Running script to invoke PAWS applications"
echo "Arguments = $*"
echo "-------------------------------------------"

set workdir = $1 ; shift

echo "Changing to directory $workdir ..."
cd $workdir
echo "-------------------------------------------"

echo "Running command $* ..."
echo "-------------------------------------------"
$*

# start a shell; exiting from this will quit the script
/bin/csh


# ACL:rcsinfo
#  ----------------------------------------------------------------------
#  $RCSfile: keepit,v $   $Author: adelmann $
#  $Revision: 1.1.1.1 $   $Date: 2000/11/30 21:03:57 $
#  ----------------------------------------------------------------------
# ACL:rcsinfo
