##
# @file visualize.py
# @author Matthias Frey
# @date 14. October 2016, LBNL
# 
# @pre Environment variable OPAL_BUILD has to be set.
# @details Plot the electric self-field, density and self-field
# potential using the yt framework.
# 1. mpirun -np #cores testSolver
# 2. python visualize.py (make sure you sourced the yt directory $YT_DIR/yt-x86_64/bin/activate)
# @brief Slice plots of plotfiles generated by writePlotFile.H

import os
import yt

opal = os.environ['OPAL_BUILD']
ds = yt.load(opal + "ippl/test/AMR/plt0000", unit_system='accel')

ds.print_stats()


print ("Field list:")
print (ds.field_list)

print ("Derived field list:")
print (ds.derived_field_list)


slc = yt.SlicePlot(ds, normal='z', fields='rho')
slc.set_unit('rho', 'e/m**3')
slc.annotate_grids()
slc.save()

#slc = yt.ProjectionPlot(ds, 'x', fields='rho')
#slc.annotate_grids()
#slc.save()


#slc = yt.ProjectionPlot(ds, 'y', fields='rho')
#slc.annotate_grids()
#slc.save()

#slc = yt.ProjectionPlot(ds, 'z', fields='rho') #, width=(0.05, 0.05))
#slc.annotate_grids()
#slc.save()

slc = yt.SlicePlot(ds, normal='z', fields='Ex')
slc.set_unit('Ex', 'V/m')
slc.annotate_grids()
slc.save()

slc = yt.SlicePlot(ds, normal='z', fields='Ey')
slc.set_unit('Ey', 'V/m')
slc.annotate_grids()
slc.save()

#slc = yt.SlicePlot(ds, normal='x', fields='Ez')
#slc.annotate_grids()
#slc.save()

slc = yt.SlicePlot(ds, normal='z', fields='potential')
slc.set_unit('potential', 'V')
slc.annotate_grids()
slc.save()

ad = ds.all_data()

print ( ad.quantities.extrema("rho") )

rho = ad['rho']
print ( "Density: ", rho.max() )
print ( "Density: ", rho.max().in_units('e/m**3') )
print ( "Potential: ", ad['potential'].max() )
print ( "Potential: ", ad['potential'].in_units('V').max() )
#dx = ad['dx']
#print ( "dx = ", dx )